#!/bin/bash

sudo apt-get update &> /dev/null
sudo apt-get upgrade -y 
sudo apt-get autoremove 1> /dev/null
sudo apt-get autoclean 	1> /dev/null
sudo apt-get clean 1> /dev/null

echo ""
echo "System upgrade performed at $(date)"

